name: check_code_quality
on: pull_request
jobs:
  black:
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.7
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black
          pip install pylint
      - run: |
          black --check --verbose app.py init_db.py
      - run: |
          pylint app.py init_db.py

